[package]
name = "ascent-provenance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Why and positive Boolean provenance for unmodified Ascent"

[dependencies]
ascent.workspace = true
ascent-provenance-macros = { version = "=0.1.0", path = "../ascent-provenance-macros" }

[dev-dependencies]
ascent-byods-rels = { version = "=0.8.1", default-features = false }
